#pragma once

#include "c_ui/workbenches/common/RibbonCommon.h"

namespace RibbonIconMaps {

static const RibbonCommon::IconMapItem kStartIconMap[] = {
        { QStringLiteral("快速导入"),  ":/start_icons01/icons_other/start_icons/quick_input.png" },
        { QStringLiteral("体积导入"),  ":/start_icons01/icons_other/start_icons/reload_volume_data.png" },
        { QStringLiteral("显示模式"),  ":/start_icons01/icons_other/start_icons/display_pattern.png" },
        { QStringLiteral("水平/窗口模式"),  ":/start_icons01/icons_other/start_icons/shuipingchuangkou.png" },
        { QStringLiteral("厚板"),  ":/start_icons01/icons_other/start_icons/thick_board.PNG" },
        { QStringLiteral("裁剪当前切片图"),  ":/start_icons01/icons_other/start_icons/clip_plane.png" },
        { QStringLiteral("对齐"),  ":/start_icons01/icons_other/start_icons/simple_align.png" },
        { QStringLiteral("指示器"),  ":/start_icons01/icons_other/start_icons/indicator.PNG" },
        { QStringLiteral("距离"),  ":/start_icons01/icons_other/start_icons/distance.PNG" },
        { QStringLiteral("角度(4个点)"),      ":/start_icons01/icons_other/start_icons/angle_4points.PNG" },
        { QStringLiteral("角度(3个点)"),        ":/start_icons01/icons_other/start_icons/angle_3points.PNG" },
        { QStringLiteral("折线长度"),        ":/start_icons01/icons_other/start_icons/fold_line_length.PNG" },
        { QStringLiteral("最小/最大距离"),        ":/start_icons01/icons_other/start_icons/max_min_distance.PNG" },
        { QStringLiteral("卡尺"),":/start_icons01/icons_other/start_icons/caliper.PNG" },
        { QStringLiteral("捕捉模式"),":/start_icons01/icons_other/start_icons/capture_pattern.PNG" },
        { QStringLiteral("重新捕捉量具控点"),  ":/start_icons01/icons_other/start_icons/re_capture_measure_tool_control_point.PNG" },
        { QStringLiteral("创建报告"),  ":/start_icons01/icons_other/start_icons/create_report.PNG" },
        { QStringLiteral("创建书签"),  ":/start_icons01/icons_other/start_icons/create_bookmark.PNG" },
        { QStringLiteral("书签编辑器"),  ":/start_icons01/icons_other/start_icons/bookmark_editor.PNG" },
        { QStringLiteral("保存图像/影片"),  ":/start_icons01/icons_other/start_icons/save_image.png" },
    };

static const RibbonCommon::IconMapItem kEditIconMap[] = {
        { QStringLiteral("撤销"), ":/icons/icons/undo.png" },
        { QStringLiteral("重做"), ":/icons/icons/redo.png" },
        { QStringLiteral("释放内存/清除撤销队列"), ":/icons/icons/free_memory.png" },
        { QStringLiteral("剪切"), ":/icons/icons/cut.png" },
        { QStringLiteral("复制"), ":/icons/icons/copy.png" },
        { QStringLiteral("粘贴"), ":/icons/icons/paste.png" },
        { QStringLiteral("删除"), ":/icons/icons/delete.png" },
        { QStringLiteral("创建对象组"), ":/icons/icons/create_obj_group.png" },
        { QStringLiteral("取消对象组"), ":/icons/icons/cancel_obj_group.png" },
        { QStringLiteral("转换为"), ":/icons/icons/trans_pull_down_menu/trans.png" },
        { QStringLiteral("属性"), ":/icons/icons/property.png" },
        { QStringLiteral("旋转"), ":/icons/icons/spin.png" },
        { QStringLiteral("移动"), ":/icons/icons/move.png" },
        { QStringLiteral("复制可视状态"), ":/icons/icons/copy_visible_status.png" },
        { QStringLiteral("粘贴可视状态"), ":/icons/icons/paste_visible_status.png" },
        { QStringLiteral("复制元信息"), ":/icons/icons/copy_meta.png" },
        { QStringLiteral("粘贴元信息"), ":/icons/icons/paste_meta.png" },
        { QStringLiteral("动态重命名"), ":/icons/icons/dynamic_rename.png" },
    };

static const RibbonCommon::IconMapItem kVolumeIconMap[] = {
        { QStringLiteral("拆分体积"),  ":/volume_icons/icons_other/volume_icons/split_volume.png" },
        { QStringLiteral("表面测定"),  ":/volume_icons/icons_other/volume_icons/surface_measure_pull_down_menu/surface_measure_and_based_on_iosvalue.png" },
        { QStringLiteral("删除表面测定"), ":/volume_icons/icons_other/volume_icons/delete_surface_measure.png" },
        { QStringLiteral("体积数据"),  ":/volume_icons_2/icons_other/volume_icons/volume_data_pull_down_menu/volume_data.png" },
        { QStringLiteral("基于特征的缩放"),  ":/volume_icons/icons_other/volume_icons/feature_scale.png" },
        { QStringLiteral("手动缩放"),  ":/volume_icons/icons_other/volume_icons/manual_scale.png" },
        { QStringLiteral("绘制数据"),  ":/icons/icons/delete.png" },
        { QStringLiteral("选择颜色"),  ":/volume_icons/icons_other/volume_icons/choose_color.png" },
        { QStringLiteral("填充"),  ":/volume_icons/icons_other/volume_icons/fill.png" },
        { QStringLiteral("自适应高斯"),      ":/volume_icons/icons_other/volume_icons/adaptive_gaussian.png" },
        { QStringLiteral("非局部均值"),        ":/volume_icons/icons_other/volume_icons/non_local_mean.png" },
        { QStringLiteral("卷积"),        ":/volume_icons/icons_other/volume_icons/convolution.png" },
        { QStringLiteral("高斯"),        ":/volume_icons/icons_other/volume_icons/gaussian.png" },
        { QStringLiteral("框"),":/volume_icons/icons_other/volume_icons/frame.png" },
        { QStringLiteral("偏差"),":/volume_icons/icons_other/volume_icons/deviation.png" },
        { QStringLiteral("中值"),  ":/volume_icons/icons_other/volume_icons/mid_value.png" },
        { QStringLiteral("侵蚀"),  ":/volume_icons/icons_other/volume_icons/erosion.png" },
        { QStringLiteral("膨胀"),  ":/volume_icons/icons_other/volume_icons/dilation.png" },
        { QStringLiteral("应用不透明映射"),  ":/volume_icons/icons_other/volume_icons/apply_opacity_mapping.png" },
        { QStringLiteral("FIB-SEM 修正"),  ":/volume_icons/icons_other/volume_icons/FIB-SEM_fix.png" },
        { QStringLiteral("合并和重新采样"),  ":/volume_icons/icons_other/volume_icons/merge_and_resample.png" },
        { QStringLiteral("体积投影器"),  ":/volume_icons/icons_other/volume_icons/volume_projector.png" },
    };

static const RibbonCommon::IconMapItem kSelectIconMap[] = {
        { QStringLiteral("导航光标"),  ":/select_icons/icons_other/select_icons/navigation_cursor.png" },
        { QStringLiteral("裁剪"),  ":/select_icons_2/icons_other/select_icons/clip_pull_down_menu/clip_plane.png" },
        { QStringLiteral("选择对象(3D)"), ":/select_icons_2/icons_other/select_icons/choose_obj_3D_pull_down_menu/rectangle2.png" },
        { QStringLiteral("绘制"),  ":/select_icons/icons_other/select_icons/draw.png" },
        { QStringLiteral("矩形"),  ":/select_icons/icons_other/select_icons/rectangle.png" },
        { QStringLiteral("圆角矩形"),  ":/select_icons/icons_other/select_icons/round_rectangle.png" },
        { QStringLiteral("椭圆"),  ":/select_icons/icons_other/select_icons/ellipse.png" },
        { QStringLiteral("折线"),  ":/select_icons/icons_other/select_icons/polyline.png" },
        { QStringLiteral("多边形套索"),  ":/select_icons/icons_other/select_icons/lasso.png" },
        { QStringLiteral("折线3D"),      ":/select_icons/icons_other/select_icons/polyline3D.png" },
        { QStringLiteral("矩形3D"),        ":/select_icons/icons_other/select_icons/rectangle3D.png" },
        { QStringLiteral("椭圆3D"),        ":/select_icons/icons_other/select_icons/ellipse3D.png" },
        { QStringLiteral("来自灰度值的ROI"),        ":/select_icons_2/icons_other/select_icons/from_grayscale_value_ROI_pull_down_menu/region_grow.png" },
        { QStringLiteral("来自对象的ROI"),":/select_icons_2/icons_other/select_icons/from_obj_ROI_pull_down_menu/from_obj_ROI.png" },
        { QStringLiteral("绘制&分割"),":/select_icons/icons_other/select_icons/draw_segmentation.png" },
        { QStringLiteral("绘制分割应用"),  ":/select_icons/icons_other/select_icons/apply_draw_and_segmentation_model.png" },
        { QStringLiteral("深度分割"),  ":/select_icons/icons_other/select_icons/deep_segmentation.png" },
        { QStringLiteral("侵蚀/膨胀"),  ":/select_icons/icons_other/select_icons/erosion_dilation.png" },
        { QStringLiteral("平滑处理"),  ":/select_icons/icons_other/select_icons/smooth_process.png" },
        { QStringLiteral("裂纹分割"),  ":/select_icons/icons_other/select_icons/crack_segmentation.png" },
        { QStringLiteral("缩放"),  ":/select_icons/icons_other/select_icons/scale.png" },
        { QStringLiteral("修正"),  ":/select_icons/icons_other/select_icons/fix.png" },
        { QStringLiteral("添加ROI到ROI"),  ":/select_icons_2/icons_other/select_icons/action_icon_group/add_ROI_to_ROI.png" },
        { QStringLiteral("从ROI减去ROI"),  ":/select_icons_2/icons_other/select_icons/action_icon_group/form_ROI_subtract_ROI.png" },
        { QStringLiteral("拆分ROI"),  ":/select_icons_2/icons_other/select_icons/action_icon_group/detach_ROI.png" },
        { QStringLiteral("清理ROI"),  ":/select_icons_2/icons_other/select_icons/action_icon_group/clean_ROI.png" },
        { QStringLiteral("ROI与ROI相交"),  ":/select_icons_2/icons_other/select_icons/action_icon_group/ROI_and_ROI_intersection.png" },
        { QStringLiteral("合并ROI"),  ":/select_icons_2/icons_other/select_icons/action_icon_group/merge_ROI.png" },
        { QStringLiteral("反转ROI"),  ":/select_icons_2/icons_other/select_icons/action_icon_group/reverse_ROI.png" },
        { QStringLiteral("更改ROI精度"),  ":/select_icons_2/icons_other/select_icons/action_icon_group/change_ROI_precision.png" },
        { QStringLiteral("提取ROI"),  ":/select_icons_2/icons_other/select_icons/action_icon_group/extract_ROI.png" },
        { QStringLiteral("重新采样ROI"),  ":/select_icons_2/icons_other/select_icons/action_icon_group/sample_ROI.png" },
        { QStringLiteral("ROI渲染"),  ":/select_icons_2/icons_other/select_icons/action_icon_group/ROI_render.png" },
        { QStringLiteral("粘贴带选项的ROI"),  ":/select_icons/icons_other/select_icons/paste_with_option_ROI.png" },
        { QStringLiteral("ROI模板"),  ":/select_icons_2/icons_other/select_icons/ROI_template_pull_down_menu/ROI_template.png" },
    };

static const RibbonCommon::IconMapItem kAlignIconMap[] = {
        { QStringLiteral("最佳拟合对齐"),  ":/alignment_icons/icons_other/align_icons/best_fit_align.png" },
        { QStringLiteral("3-2-1对齐"),  ":/alignment_icons/icons_other/align_icons/3-2-1_align.png" },
        { QStringLiteral("基于特征的对齐"), ":/alignment_icons/icons_other/align_icons/based_on_feature_align.png" },
        { QStringLiteral("按次序对齐"),  ":/alignment_icons/icons_other/align_icons/in_order_align.png" },
        { QStringLiteral("RPS对齐"),  ":/alignment_icons/icons_other/align_icons/RPS_align.png" },
        { QStringLiteral("基于几何元素的拟合"),  ":/alignment_icons/icons_other/align_icons/based_on_geometry_element_best_fit.png" },
        { QStringLiteral("编辑当前对齐"),  ":/alignment_icons/icons_other/align_icons/edit_current_align.png" },
        { QStringLiteral("简单3-2-1对齐"),  ":/alignment_icons/icons_other/align_icons/simple_3-2-1_align.png" },
        { QStringLiteral("简单对齐"),  ":/alignment_icons/icons_other/align_icons/simple_align.png" },
        { QStringLiteral("将切片图对齐到对象"),      ":/alignment_icons/icons_other/align_icons/slice_images_align_to_obj.png" },
        { QStringLiteral("坐标系原点"),        ":/alignment_icons/icons_other/align_icons/coordinate_origin.png" },
        { QStringLiteral("坐标系编辑器"),        ":/alignment_icons/icons_other/align_icons/coordinate_system_editor.png" },
        { QStringLiteral("存储对齐"),        ":/alignment_icons/icons_other/align_icons/store_align.png" },
        { QStringLiteral("应用对齐"),":/alignment_icons/icons_other/align_icons/apply_align.png" },
        { QStringLiteral("复制转换"),":/alignment_icons/icons_other/align_icons/copy_transformation.png" },
        { QStringLiteral("粘贴转换"),  ":/alignment_icons/icons_other/align_icons/paste_transformation.png" },
        { QStringLiteral("重置转换"),  ":/alignment_icons/icons_other/align_icons/reset_transformation.png" },
        { QStringLiteral("锁定"),  ":/alignment_icons/icons_other/align_icons/lock.png" },
        { QStringLiteral("解锁"),  ":/alignment_icons/icons_other/align_icons/unlock.png" },
    };

static const RibbonCommon::IconMapItem kGeoIconMap[] = {
        { QStringLiteral("自动"),  ":/geometry_icons/icons_other/geometry_icons/auto.PNG" },
        { QStringLiteral("点"),  ":/geometry_icons/icons_other/geometry_icons/point.PNG" },
        { QStringLiteral("线"), ":/geometry_icons/icons_other/geometry_icons/line.PNG" },
        { QStringLiteral("圆"),  ":/geometry_icons/icons_other/geometry_icons/circle.PNG" },
        { QStringLiteral("角圆"),  ":/geometry_icons/icons_other/geometry_icons/corner_circle.PNG" },
        { QStringLiteral("平面"),  ":/geometry_icons/icons_other/geometry_icons/plane.PNG" },
        { QStringLiteral("球体"),  ":/geometry_icons/icons_other/geometry_icons/sqhere.PNG" },
        { QStringLiteral("圆柱"),  ":/geometry_icons/icons_other/geometry_icons/cylinder.PNG" },
        { QStringLiteral("圆锥"),  ":/geometry_icons/icons_other/geometry_icons/cone.PNG" },
        { QStringLiteral("环面"),      ":/geometry_icons/icons_other/geometry_icons/torus.PNG" },
        { QStringLiteral("自由造型线"),        ":/geometry_icons/icons_other/geometry_icons/freedom_modeling_line.PNG" },
        { QStringLiteral("自由造型表面"),        ":/geometry_icons/icons_other/geometry_icons/freedom_modeling_surface.PNG" },
        { QStringLiteral("定义几何元素"),        ":/geometry_icons/icons_other/geometry_icons/define_geometry_element.png" },
        { QStringLiteral("显示拟合点"),":/geometry_icons/icons_other/geometry_icons/display_fit_point.PNG" },
        { QStringLiteral("隐藏拟合点"),":/geometry_icons/icons_other/geometry_icons/hide_fit_point.PNG" },
        { QStringLiteral("切换拟合点可见性"),  ":/geometry_icons/icons_other/geometry_icons/switch_fit_point_visibility.PNG" },
        { QStringLiteral("更新CM对象"),  ":/geometry_icons02/icons_other/geometry_icons/update_CM_obj.PNG" },
        { QStringLiteral("删除未使用的CM对象"),  ":/geometry_icons/icons_other/geometry_icons/delete_unused_CM_obj.PNG" },
        { QStringLiteral("替换几何元素"),  ":/geometry_icons/icons_other/geometry_icons/replace_geometry_element.PNG" },
        { QStringLiteral("相交"),  ":/geometry_icons/icons_other/geometry_icons/intersect.PNG" },
        { QStringLiteral("对称元素"),  ":/geometry_icons/icons_other/geometry_icons/symmetry_element.PNG" },
        { QStringLiteral("修改尺寸"),  ":/geometry_icons/icons_other/geometry_icons/modify_size.PNG" },
        { QStringLiteral("组合"),  ":/geometry_icons/icons_other/geometry_icons/combine.PNG" },
        { QStringLiteral("转换"),  ":/geometry_icons/icons_other/geometry_icons/transformation.PNG" },
        { QStringLiteral("规则元素"),  ":/geometry_icons/icons_other/geometry_icons/regularize_element.PNG" },
        { QStringLiteral("投影"),  ":/geometry_icons/icons_other/geometry_icons/projection.PNG" },
        { QStringLiteral("提取最小/最大点"),  ":/geometry_icons/icons_other/geometry_icons/extract_max_min_value.PNG" },
        { QStringLiteral("提取中轴线"),  ":/geometry_icons/icons_other/geometry_icons/extract_mid_axis.PNG" },
        { QStringLiteral("转化并导出"),  ":/geometry_icons02/icons_other/geometry_icons/transformation_and_export_pull_down_menu/save_fit_point_info.PNG" },
    };

static const RibbonCommon::IconMapItem kMeasureIconMap[] = {
        { QStringLiteral("尺寸标注"),  ":/new/prefix1/icons_other/measure_icons/size_label.PNG" },
        { QStringLiteral("线性尺寸"),  ":/new/prefix1/icons_other/measure_icons/linear_dimension.PNG" },
        { QStringLiteral("直线度"), ":/measure_icons/icons_other/measure_icons/straightness.PNG" },
        { QStringLiteral("平面度"),  ":/measure_icons/icons_other/measure_icons/flatness.PNG" },
        { QStringLiteral("圆度"),  ":/measure_icons/icons_other/measure_icons/roundness.PNG" },
        { QStringLiteral("圆柱度"),  ":/measure_icons/icons_other/measure_icons/Cylindricity.PNG" },
        { QStringLiteral("圆锥度"),  ":/measure_icons/icons_other/measure_icons/cone_degree.PNG" },
        { QStringLiteral("球度"),  ":/measure_icons/icons_other/measure_icons/sqhere_degree.PNG" },
        { QStringLiteral("垂直度"),  ":/measure_icons/icons_other/measure_icons/perpendicularity.PNG" },
        { QStringLiteral("平行度"),      ":/measure_icons/icons_other/measure_icons/Parallelism.PNG" },
        { QStringLiteral("倾斜度"),        ":/measure_icons/icons_other/measure_icons/angularity.PNG" },
        { QStringLiteral("位置度"),        ":/measure_icons/icons_other/measure_icons/location_degree.PNG" },
        { QStringLiteral("同轴度"),        ":/measure_icons/icons_other/measure_icons/Coaxiality.PNG" },
        { QStringLiteral("对称度"),":/measure_icons/icons_other/measure_icons/symmetry_degree.PNG" },
        { QStringLiteral("线轮廓度"),":/measure_icons/icons_other/measure_icons/line_profile.PNG" },
        { QStringLiteral("面轮廓度"),  ":/measure_icons/icons_other/measure_icons/surface_profile.PNG" },
        { QStringLiteral("圆跳动"),  ":/measure_icons/icons_other/measure_icons/circle_runout.PNG" },
        { QStringLiteral("全跳动"),  ":/measure_icons/icons_other/measure_icons/total_runout.PNG" },
        { QStringLiteral("设置"),  ":/new/prefix1/icons_other/measure_icons/option_pull_down_menu/setting.PNG" },
        { QStringLiteral("指示器"),  ":/new/prefix1/icons_other/measure_icons/indicator.PNG" },
        { QStringLiteral("量具"),  ":/new/prefix1/icons_other/measure_icons/measure_tool_pull_down_menu/measure_tool.PNG" },
        { QStringLiteral("捕捉模式"),  ":/new/prefix1/icons_other/measure_icons/capture_pattern_pull_down_menu/capture_pattern.PNG" },
        { QStringLiteral("重新捕捉量具控点"),  ":/new/prefix1/icons_other/measure_icons/re_capture_measure_tool_control_point.PNG" },
        { QStringLiteral("测量模板"),  ":/new/prefix1/icons_other/measure_icons/measure_template_pull_down_menu/measure_template.PNG" },
        { QStringLiteral("量具模板"),  ":/new/prefix1/icons_other/measure_icons/measure_tool_template_pull_down_menu/measure_tool_template.PNG" },
        { QStringLiteral("指示器模板"),  ":/new/prefix1/icons_other/measure_icons/indicator_template_pull_down_menu/indicator_template.PNG" },
        { QStringLiteral("公差注解"),  ":/new/prefix1/icons_other/measure_icons/tolerance_annotation.PNG" },
        { QStringLiteral("CM结果"),  ":/new/prefix1/icons_other/measure_icons/CM_result.PNG" },
    };

static const RibbonCommon::IconMapItem kCadIconMap[] = {
        { QStringLiteral("简化表面网格"),  ":/cad_icons/icons_other/CAD_surfacemesh_icons/simplify_surface_mesh.PNG" },
        { QStringLiteral("删除孤立的分量"),  ":/cad_icons/icons_other/CAD_surfacemesh_icons/delete_lonely_component.PNG" },
        { QStringLiteral("翻转表面方向"), ":/cad_icons/icons_other/CAD_surfacemesh_icons/reverse_surface_direction.PNG" },
        { QStringLiteral("重新计算CAD网格"),  ":/cad_icons/icons_other/CAD_surfacemesh_icons/re-cal_CAD_mesh.PNG" },
        { QStringLiteral("合并表面网格对象"),  ":/cad_icons/icons_other/CAD_surfacemesh_icons/merge_surface_mesh_obj.PNG" },
        { QStringLiteral("变形网格"),  ":/cad_icons/icons_other/CAD_surfacemesh_icons/deformation_mesh.PNG" },
        { QStringLiteral("模具修正"),  ":/cad_icons/icons_other/CAD_surfacemesh_icons/mold_modify.PNG" },
        { QStringLiteral("补偿网格"),  ":/cad_icons/icons_other/CAD_surfacemesh_icons/compensation_mesh.PNG" },
        { QStringLiteral("迭代补偿网格"),  ":/cad_icons/icons_other/CAD_surfacemesh_icons/lteration_compensation_mesh.PNG" },
        { QStringLiteral("变形场"),      ":/cad_icons/icons_other/CAD_surfacemesh_icons/deformation_field.PNG" },
    };

static const RibbonCommon::IconMapItem kAnaIconMap[] = {
        { QStringLiteral("注解"),  ":/analyisis_icons/icons_other/analysis_icons/annotation.PNG" },
        { QStringLiteral("实时值"),  ":/analyisis_icons/icons_other/analysis_icons/realtime_value_on.PNG" },
        { QStringLiteral("孔隙/夹杂物"), ":/analysis_icons02/icons_other/analysis_icons/Pores_and_inclusions_pull_down_menu/a.PNG" },
        { QStringLiteral("P203"),  ":/analyisis_icons/icons_other/analysis_icons/P203.PNG" },
        { QStringLiteral("P202/P201"),  ":/analyisis_icons/icons_other/analysis_icons/P202_P201.PNG" },
        { QStringLiteral("设计件/实物对比"),  ":/analyisis_icons/icons_other/analysis_icons/design_to_actual_compare.PNG" },
        { QStringLiteral("壁厚"),  ":/analyisis_icons/icons_other/analysis_icons/wall_thickness.PNG" },
        { QStringLiteral("位移"),  ":/analyisis_icons/icons_other/analysis_icons/displacement.PNG" },
        { QStringLiteral("纤维复合材料"),  ":/analyisis_icons/icons_other/analysis_icons/fiber_recombination_material.PNG" },
        { QStringLiteral("泡状/粉末结构"),      ":/analyisis_icons/icons_other/analysis_icons/paozhuang_fenmu_struct.PNG" },
        { QStringLiteral("数字体积相关计算"),        ":/analyisis_icons/icons_other/analysis_icons/data_volume_cal.PNG" },
        { QStringLiteral("灰度值"),        ":/analyisis_icons/icons_other/analysis_icons/grey_value.PNG" },
        { QStringLiteral("数据质量"),        ":/analyisis_icons/icons_other/analysis_icons/data_quality.PNG" },
        { QStringLiteral("切片图面积"),":/analyisis_icons/icons_other/analysis_icons/slice_area.PNG" },
        { QStringLiteral("OCR"),":/analyisis_icons/icons_other/analysis_icons/OCR.PNG" },
        { QStringLiteral("夹紧模拟"),  ":/analyisis_icons/icons_other/analysis_icons/clip_simulation.PNG" },
        { QStringLiteral("结构力学模拟"),  ":/analyisis_icons/icons_other/analysis_icons/struct_simulation.PNG" },
        { QStringLiteral("传递现象"),  ":/analysis_icons02/icons_other/analysis_icons/transfor_phenomenon_pull_down_menu/transfer_phenomenon.PNG" },
        { QStringLiteral("电池极片对齐分析"),  ":/analyisis_icons/icons_other/analysis_icons/battery_analysis.PNG" },
        { QStringLiteral("导入集成网格"),  ":/analyisis_icons/icons_other/analysis_icons/input_integration_mesh.PNG" },
        { QStringLiteral("创建集成网格"),  ":/analysis_icons02/icons_other/analysis_icons/create_integration_mesh_pull_down_menu/create_integration_mesh.PNG" },
        { QStringLiteral("评估"),  ":/analysis_icons02/icons_other/analysis_icons/evaluate_pull_down_menu/evaluate.PNG" },
        { QStringLiteral("更新所有分析"),  ":/analyisis_icons/icons_other/analysis_icons/update_analysis.PNG" },
    };

static const RibbonCommon::IconMapItem kReportIconMap[] = {
        { QStringLiteral("创建报告"),  ":/report_icons/icons_other/report_icons/create_report.PNG" },
        { QStringLiteral("打开报告"),  ":/report_icons/icons_other/report_icons/open_report.PNG" },
        { QStringLiteral("更新报告"), ":/report_icons/icons_other/report_icons/updata_report.PNG" },
        { QStringLiteral("删除报告"),  ":/report_icons/icons_other/report_icons/delelte_report.PNG" },
        { QStringLiteral("导出PDF"),  ":/report_icons/icons_other/report_icons/output_PDF.PNG" },
        { QStringLiteral("导出HTML"),  ":/report_icons/icons_other/report_icons/output_html.png" },
        { QStringLiteral("导出默认布局"),  ":/report_icons/icons_other/report_icons/output_default_layout.png" },
        { QStringLiteral("导出特定布局"),  ":/report_icons/icons_other/report_icons/output_special_layout.png" },
        { QStringLiteral("创建书签"),  ":/report_icons/icons_other/report_icons/create_bookmark.PNG" },
        { QStringLiteral("书签编辑器"),      ":/report_icons/icons_other/report_icons/bookmark_editor.PNG" },
        { QStringLiteral("保存图像"),        ":/report_icons/icons_other/report_icons/save_image.png" },
        { QStringLiteral("保存影片/图像堆栈"),        ":/report_icons/icons_other/report_icons/save_movie_image_stack.png" },
        { QStringLiteral("导出为Q-DAS文件"),        ":/report_icons/icons_other/report_icons/output_Q_DAS_document.png" },
    };

static const RibbonCommon::IconMapItem kAniIconMap[] = {
        { QStringLiteral("尺寸标注"),  ":/new/prefix1/icons_other/measure_icons/size_label.PNG" },
        { QStringLiteral("线性尺寸"),  ":/new/prefix1/icons_other/measure_icons/linear_dimension.PNG" },
        { QStringLiteral("直线度"), ":/measure_icons/icons_other/measure_icons/straightness.PNG" },
        { QStringLiteral("平面度"),  ":/measure_icons/icons_other/measure_icons/flatness.PNG" },
        { QStringLiteral("圆度"),  ":/measure_icons/icons_other/measure_icons/roundness.PNG" },
        { QStringLiteral("圆柱度"),  ":/measure_icons/icons_other/measure_icons/Cylindricity.PNG" },
        { QStringLiteral("圆锥度"),  ":/measure_icons/icons_other/measure_icons/cone_degree.PNG" },
        { QStringLiteral("球度"),  ":/measure_icons/icons_other/measure_icons/sqhere_degree.PNG" },
        { QStringLiteral("垂直度"),  ":/measure_icons/icons_other/measure_icons/perpendicularity.PNG" },
        { QStringLiteral("平行度"),      ":/measure_icons/icons_other/measure_icons/Parallelism.PNG" },
        { QStringLiteral("倾斜度"),        ":/measure_icons/icons_other/measure_icons/angularity.PNG" },
        { QStringLiteral("位置度"),        ":/measure_icons/icons_other/measure_icons/location_degree.PNG" },
        { QStringLiteral("同轴度"),        ":/measure_icons/icons_other/measure_icons/Coaxiality.PNG" },
        { QStringLiteral("对称度"),":/measure_icons/icons_other/measure_icons/symmetry_degree.PNG" },
        { QStringLiteral("线轮廓度"),":/measure_icons/icons_other/measure_icons/line_profile.PNG" },
        { QStringLiteral("面轮廓度"),  ":/measure_icons/icons_other/measure_icons/surface_profile.PNG" },
        { QStringLiteral("圆跳动"),  ":/measure_icons/icons_other/measure_icons/circle_runout.PNG" },
        { QStringLiteral("全跳动"),  ":/measure_icons/icons_other/measure_icons/total_runout.PNG" },
        { QStringLiteral("设置"),  ":/new/prefix1/icons_other/measure_icons/option_pull_down_menu/setting.PNG" },
        { QStringLiteral("指示器"),  ":/new/prefix1/icons_other/measure_icons/indicator.PNG" },
        { QStringLiteral("量具"),  ":/new/prefix1/icons_other/measure_icons/measure_tool_pull_down_menu/measure_tool.PNG" },
        { QStringLiteral("捕捉模式"),  ":/new/prefix1/icons_other/measure_icons/capture_pattern_pull_down_menu/capture_pattern.PNG" },
        { QStringLiteral("重新捕捉量具控点"),  ":/new/prefix1/icons_other/measure_icons/re_capture_measure_tool_control_point.PNG" },
        { QStringLiteral("测量模板"),  ":/new/prefix1/icons_other/measure_icons/measure_template_pull_down_menu/measure_template.PNG" },
        { QStringLiteral("量具模板"),  ":/new/prefix1/icons_other/measure_icons/measure_tool_template_pull_down_menu/measure_tool_template.PNG" },
        { QStringLiteral("指示器模板"),  ":/new/prefix1/icons_other/measure_icons/indicator_template_pull_down_menu/indicator_template.PNG" },
        { QStringLiteral("公差注解"),  ":/new/prefix1/icons_other/measure_icons/tolerance_annotation.PNG" },
        { QStringLiteral("CM结果"),  ":/new/prefix1/icons_other/measure_icons/CM_result.PNG" },
    };

static const RibbonCommon::IconMapItem kWindowIconMap[] = {
        { QStringLiteral("四分"),  ":/window_icons02/icons_other/window_icons/layout_section_icon_group/four.PNG" },
        { QStringLiteral("切片图靠左"),  ":/window_icons02/icons_other/window_icons/layout_section_icon_group/slice_left.PNG" },
        { QStringLiteral("切片图靠右"), ":/window_icons02/icons_other/window_icons/layout_section_icon_group/slice_right.PNG" },
        { QStringLiteral("切片图靠下"),  ":/window_icons02/icons_other/window_icons/layout_section_icon_group/slice_down.PNG" },
        { QStringLiteral("旋转"),  ":/window_icons02/icons_other/window_icons/layout_section_icon_group/spin.PNG" },
        { QStringLiteral("四分，分布图"),  ":/window_icons02/icons_other/window_icons/layout_section_icon_group/four__.PNG" },
        { QStringLiteral("非平面"),  ":/window_icons02/icons_other/window_icons/layout_section_icon_group/non_plane.PNG" },
        { QStringLiteral("布局编辑器"),  ":/window_icons/icons_other/window_icons/layout_editor.PNG" },
        { QStringLiteral("2D背景"),  ":/window_icons/icons_other/window_icons/2D_background.png" },
        { QStringLiteral("3D背景"),      ":/window_icons/icons_other/window_icons/3D_background.png" },
        { QStringLiteral("放大"),        ":/window_icons/icons_other/window_icons/zoom_in.PNG" },
        { QStringLiteral("缩小"),        ":/window_icons/icons_other/window_icons/zoom_out.PNG" },
        { QStringLiteral("体素分辨率"),        ":/window_icons/icons_other/window_icons/voxel_resolution.PNG" },
        { QStringLiteral("设置缩放比例"),":/window_icons/icons_other/window_icons/set_zoom_ratio.PNG" },
        { QStringLiteral("调整对象以适应窗口"),":/window_icons/icons_other/window_icons/fit_obj_to_window.PNG" },
        { QStringLiteral("调整场景以适应窗口"),  ":/window_icons/icons_other/window_icons/fit_scene_to_window.PNG" },
        { QStringLiteral("重置"),  ":/window_icons/icons_other/window_icons/reset_zoom.PNG" },
        { QStringLiteral("显示模式"),  ":/window_icons02/icons_other/window_icons/display_pattern_pull_down_menu/display_pattern.png" },
        { QStringLiteral("厚板"),  ":/window_icons/icons_other/window_icons/thick_board.PNG" },
        { QStringLiteral("切片图步宽"),  ":/window_icons/icons_other/window_icons/slice_step_size.PNG" },
        { QStringLiteral("水平/窗口模式"),  ":/window_icons/icons_other/window_icons/horizontal_window_pattern.png" },
        { QStringLiteral("标尺"),  ":/window_icons/icons_other/window_icons/ruler.PNG" },
        { QStringLiteral("注解"),  ":/window_icons02/icons_other/window_icons/annotation_pull_down_menu/annotation.png" },
        { QStringLiteral("文本叠加层编辑器"),  ":/window_icons/icons_other/window_icons/text_overlay_layer_editor.png" },
        { QStringLiteral("工具"),  ":/window_icons02/icons_other/window_icons/tool_pull_down_menu/same.PNG" },
        { QStringLiteral("工具停靠栏"),  ":/window_icons/icons_other/window_icons/toolbar_docking.PNG" },
        { QStringLiteral("重置工具"),  ":/window_icons/icons_other/window_icons/reset_tool.PNG" },
    };

} // namespace RibbonIconMaps
